api:
  port: 8080
elastic_cloud:
  cloud_id: ${CLOUD_ID}
  user: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
elasticsearch_local:
  hosts: ${ELASTIC_HOSTS}               # Comma separated host addresses
  user: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
elasticsearch_integration_type: LOCAL   # Options are: LOCAL / CLOUD / BONSAI
tensorflow_hub:
  model_url: https://tfhub.dev/google/universal-sentence-encoder/4
